### ISSUE TITLE
Myles Holt - Personal Success 

### ISSUE THREAD

**Issue by myholt22** [dartmouth-cs98/20w-ensemble-vr#112]
# Myles Holt | Personal Goals

*what does success for this class mean to you?*

* Create a product that can be useful or interesting to people out there who wish to use it. 
* The core features are implemented. Features such as Multiplayer would be interesting for sure, however it isn't completely necessary in order for the project to fulfill its goals. 
* Create something that hasn't already been done before. I feel that our product accomplishes this
* Learn new technology. Getting to learn Unity and Blender (what I used for modeling) has been a stressful but enlightening experience. 

*what are some challenges you foresee?*

* Difficult for multiple people to work on the same scene in Unity
* Resolving merge conflicts in a remote setting could be difficult
* Have noticed that this project likely requires you to use various software, many of which can be difficult to learn
* Typically spend a lot of time on one task. I found the animating to be particularly difficult, and the animations seemed to not work properly on many of the attempts 
* Working from home. The apartment I live in is small and there is virtually no privacy. It's just hard to focus on work in my home environment.

**Comment by timofei7** [comment]
Love the goals.  Please keep me posted on how things are going. I also do still have a VR unit if you need me to ship it.  And let me know if there's any way to help with the challenges.
