### ISSUE TITLE
James Lee | Personal Success

### ISSUE THREAD

**Issue by jamesjinlee** [dartmouth-cs98/20w-ensemble-vr#113]
James Lee | Personal Goals
- I’m primary working on modeling and animation for this project, and I don’t think the quality of the modeling is currently good enough for this project.  I want to create an environment that I am proud of, and that users will be amazed by. 
- One particular thing I would be proud of If I can implement is syncing the orchestra animations to the accompaniment music. I think that if I achieve this, it would greatly help in creating a more realistic environment.
- I also want to showcase this project in my portfolio, and hope to create a quality application that others will be impressed by.

Challenges
- One limitation is the processing power of the oculus. I haven’t added nearly as many people as I wish to, yet their animations are already beginning to lag the application.
- Another challenge is improving upon the audience members. These models were taken from resources online, and their quality isn’t the best. Perhaps I would need to find new models or create ones myself.

**Comment by timofei7** [comment]
Good goals - would love to see the synchronization. Let me know if want to discuss some optimizations for models/animations etc for the quest.
