### ISSUE TITLE
Marshall Peng | Personal Success

### ISSUE THREAD

**Issue by MarshallPeng** [dartmouth-cs98/20w-ensemble-vr#114]
# Marshall Peng | Personal Goals
*what does success for this class mean to you?*

* Success in this class means that I create a product that I am proud of, both in the quantitative/technical difficulty as well as how well polished the final product is. Mostly because I want to prove to myself that I am capable of completing a project that is non-trivial.
* Of course, this is something that I hope to be able to, in the future, show off to friends and include in my portfolio. 
* Our project actually aims to solve a problem that I've experienced for a long time, and I hope to be able to actually use this product in the future.

## Challenges
*what are some challenges you foresee?*

* There's a lot of technical difficulty associated with the project. Many of the techniques that are used, aren't really well describes / don't have nice tutorials to follow / textbook chapters. i.e Hierarchical Hidden Semi-Markov Models. Additionally, the papers that we are following don't give step by step instructions, so a lot of the work is very uncertain and slightly modified from the actual paper.
* Even if we don't get the "score following" working, *real-time* tempo estimation is also a non-trivial task which requires potentially a similar level of work as the score following. So if we do decide to jump ship, we will need to plan ahead / give enough time.
* Also I anticipate some difficulty with the transmission of data from the python script to the headset, as I'm not sure how quickly we can transmit data, whether that's via the cord, or with a UDP connection or something.

**Comment by timofei7** [comment]
Love your goals - excited to see it all come together - looks like it is!

Is the current idea that the python runs on a local computer which is also the listening device and then sends a stream to the headset?

**Comment by MarshallPeng** [comment]
Yeah, the current plan is that the python script runs locally, it listens to the incoming audio, then streams "where in the score" to the headset, which then gets the accompaniment to play the corresponding parts. This hopefully will sound more realistic than just blasting it out of the laptop since unity does a lot of the sound physics to make it sound more immersive when you walk around/turn your head.

**Comment by timofei7** [comment]
sounds like a plan!   so the local python server would connect to say the laptop microphone? something like websockets could work, depending on how much data you are sending, I think you guys had looked into that at some point last term.
